server:
  port: 8765
spring:
  application:
    name: hireme-api-gateway
  config:
    import: optional:configserver:http://localhost:8888/
  cloud:
    config:
      profile: dev
    gateway:
      discovery:
        locator:
          enabled: true
